### PR TITLE
Add vincenzobaz to the team

### PR DESCRIPTION
**Pull request by vincenzobaz**
This PR my profile to the list of team members

### CODE REVIEW

**Comment by vincenzobaz** [comment]
Addresses issue #139

**Comment by sjrd** [comment]
You will also need the `@2x` version of the picture, like in other similar PRs.

**Review by julienrf — APPROVED** [review]
Maybe the other picture is needed, indeed?

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
Oops, it conflicts with #144, do you mind fixing the conflict, @vincenzobaz?

**Review by sjrd — APPROVED** [review]

**Pull request merged**
