### PR TITLE
Minutes for meeting 22

### PR DESCRIPTION
**Pull request by SethTisue**
At the moment this is just a draft PR with a skeleton of the minutes. It will take about a week before the full text of the minutes will be filled in, since the board needs time to review that text and make sure it is accurate.

### CODE REVIEW

**Comment by SethTisue** [comment]
A draft has now been sent to the Center and the board.

**Comment by SethTisue** [comment]
There is a bit of delay finalizing the text. We're now aiming for public release on Nov 29, knock on wood.

**Comment by SethTisue** [comment]
Gears are still turning — the minutes proper are ready, but there's some wordings from the Center that's taking time to get consensus on.

**Comment by SethTisue** [comment]
A revised draft has been sent to the board.

**Comment by nmcb** [comment]
QUESTION, Mar 4: please - from a personal as well as professional point of view - when will the notes of the 22nd meeting of november last year be published ?

(the lack of urgency for transparency of due process becomes unbearable - and is a clear outlier to the normal prompt publication of prior meeting notes. - we appreciate being kept informed via this pull request's thread of comments - honestly - but time starts taking its toll - so a concrete commitment for a future date to publish the notes would be appreciated - truly yours, etc. & etc.)

**Comment by SethTisue** [comment]
> the minutes proper are ready

And are now merged. The rest is out of my hands.

**Comment by SethTisue** [comment]
(I'm already working on the minutes from the meeting we had in January, so I thought we shouldn't wait any longer before getting the November minutes out there, minus the part there has been difficulty finalizing. Another set will be along soon enough.)

**Pull request merged**
