### PR TITLE
Darja new team member and photo

### PR DESCRIPTION
**Pull request by darjutak**

### CODE REVIEW

**Comment by heathermiller** [comment]
Seems you made a mistake with the spacing in the yaml file.

**Comment by darjutak** [comment]
@propensive thank you very much!

**Comment by propensive** [comment]
@darjutak It was too easy not to do! ;)

**Comment by darjutak** [comment]
@propensive easy or not it fell off my radar and now I feel happy it's done... I guess I am getting into  the vibes of the Scala communal type of collaboration hihihi

**Pull request merged**
