### PR TITLE
make mission statement more visible

### PR DESCRIPTION
**Pull request by tgodzik**
After the changes it looks like this:

image

what do you all think?

### CODE REVIEW

**Comment by SethTisue** [comment]
fwiw the "independently" in "Independently guide and support" seems odd to me — I literally don't know what it's meant to communicate

**Comment by propensive** [comment]
@SethTisue The intention, I think, is to emphasise the Scala Center's autonomy to make decisions about its budget and projects: independence from Martin/LAMP, and independence from its sponsors. Legally, as an EPFL-governed entity, the Scala Center cannot be contractually bound to another other profit-making (or any?) entity. This was something that was made very clear to us at the time of its foundation, and the consciousness of that fact has probably crept into the marketing material...

By the way, I think that the word "new" in "A new not-for-profit..." should probably be removed now.

**Comment by SethTisue** [comment]
makes sense! (but as written, the text doesn't actually succeed in communicating that)

**Comment by tgodzik** [comment]
> By the way, I think that the word "new" in "A new not-for-profit..." should probably be removed now.

Right, that is no longer valid.

> makes sense! (but as written, the text doesn't actually succeed in communicating that)

Any idea how we should rephrase it?

**Comment by SethTisue** [comment]
> Any idea how we should rephrase it?

I think simply removing the word "independently" from the sentence would be fine. Words are at a premium in a text this short.
If it seems necessary to put it _somewhere_, how about higher up the page, here: "An independent not-for-profit center..."

**Pull request merged**
