### PR TITLE
Add sjrd to the team, make him the executive director.

### PR DESCRIPTION
**Pull request by sjrd**
Also add a distinction between active members and former members. Former members are not displayed on the Team page, but they can appear as contributors of projects. In the future we could imagine a "Former team members" section on the Team page.

### CODE REVIEW

**Comment by heathermiller** [comment]
You might want to consider updating peoples' projects cc/ @Duhemm @jvican @julienrf as well as adding new members cc/ @ alexarchambault while you're at it. 

It's a pity to only add a director but not to add the engineers that are the pillars of the center.

**Comment by sjrd** [comment]
Yup, but I kind of need a picture of Alexandre, which I don't have. It's easier if everyone adds themselves to the site. ;) Same for projects, it's easier if everyone keeps their own project list up to date.

**Comment by heathermiller** [comment]
@alexarchambault Do you have a decent picture that you can pass us to put on the website?

Also–no one has ever updated their projects without me harassing them. So, consider this part of your new job if you want the website to be somewhat accurate, @sjrd. So, double-ping to @jvican @Duhemm @julienrf. @alexarchambault, since I'm no longer around, I don't know which projects you're working on, but if it's something new, you might have to write up a little text blurb.

**Comment by alexarchambault** [comment]
I'm sending a PR to add myself (@julienrf had already pinged me for that a bit before)

**Comment by heathermiller** [comment]
Oh, and @olafurpg, your projects are also outdated 😛

**Comment by sjrd** [comment]
> So, consider this part of your new job if you want the website to be somewhat accurate, @sjrd.

Ah ah, fair enough. I will be more attentive to that, then. ;)

**Comment by julienrf** [comment]
Thanks Heather, my projects are up to date.

**Comment by SethTisue** [comment]
I checked my mailbox just now and the signed 8x10 glossies I ordered of all the Scala Center engineers _still_ haven't arrived!

**Comment by olafurpg** [comment]
Done in #74 Thanks for the reminder!

**Pull request merged**
