### PR TITLE
Update the project list that shows up on the front page

### PR DESCRIPTION
**Pull request by julienrf**
- Remove projects that we are not working on anymore
- Fix some content related to MOOCs

The new front page looks like this:

Screenshot from 2020-01-20 18-12-26

### CODE REVIEW

**Comment by SethTisue** [comment]
it seems right to emphasize active projects most strongly, but I wonder if the site should do more to tout the Center's past accomplishments as well as its present efforts

(because that touting might help maintain community confidence in the Center and also might e.g. help attract new funding)

there is a "Projects that we've worked on" header but it's pretty general

**Comment by julienrf** [comment]
That’s a good point. I intended to also update the [projects](https://scala.epfl.ch/projects.html) page in a different PR because its content is also outdated, but maybe we could highlight more in the front page the projects that we have accomplished. I don’t want to bloat the content of the front page though, what do you think of adding a link “See list of projects that we have accomplished”?

**Comment by SethTisue** [comment]
SGTM! and also, certainly my concern needn't hold up this PR

**Comment by julienrf** [comment]
@sjrd and @darjutak, would you have time to review?

**Comment by sjrd** [comment]
In principle, looks good to me.

Some additional changes that would be good:
* Remove coursier (we're not directly working on it anymore)
* Not remove scalafix? After all we're just about to write more rewrite rules for it
* Add Metals (basically through VirtusLab, but still)

**Comment by julienrf** [comment]
Thanks for the review. I’ve applied your suggestions.

**Pull request merged**
