### PR TITLE
March 2019 advisory board minutes

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
fixup in d479ba0cd47c22c47e61346388e3778f1bcc147e

**Comment by SethTisue** [comment]
* https://scala.epfl.ch/records.html
* https://scala.epfl.ch/minutes/2019/03/06/march-6-2019.html

**Comment by SethTisue** [comment]
not sure how long the deploy is supposed to take...

**Comment by SethTisue** [comment]
oh, 127e7ff811151c706dfd5aa6140d9265b64c8ad7 hasn't showed up on the site either, and that's 2+ weeks ago

@fsalvi @jvican I know nothing about the deploy pipeline for this site (that's #38), any idea what's up?

**Comment by fsalvi** [comment]
I ran it manually. Sorry, I'm out of office since a few weeks because of an accident. I will try to fix the build trigger remotely a bit later. In the mean time, I added a cron job to rebuild the website twice a day.

**Comment by sjrd** [comment]
Thank you @fsalvi!

**Comment by SethTisue** [comment]
further fixup in 744ed69a9091b573fcc6b793ae8813b388d567a9, we should hold off on tweeting until it's reach the site

draft tweet: Scala Center advisory board minutes, March 2019: Rob Norris (@tpolecat) joins board; progress on Coursier, Bloop, Metals, new MOOC, Scala Days 2019; discussions on Scala at Twitter, allowing board members to pay w/ eng instead of $, more. https://scala.epfl.ch/minutes/2019/03/06/march-6-2019.html

**Comment by SethTisue** [comment]
https://twitter.com/scala_lang/status/1118534399023206402

**Pull request merged**
