### PR TITLE
July 2023 minutes

### PR DESCRIPTION
**Pull request by SethTisue**
skeleton for now — full minutes will follow once drafted and approved by the board

### CODE REVIEW

**Comment by ckipp01** [comment]
Just about to start planning for the next meeting so I thought I'd check in here. Are we close to getting this across the finish line?

**Comment by SethTisue** [comment]
I didn't quite finish before Scala Days, but it's close. So yes, I expect to put the finishing touches on it and send it out soon.

**Comment by SethTisue** [comment]
A complete draft has now been sent to the board. So with any luck, we'll be able to publish next week.

**Comment by SethTisue** [comment]
The CI failures appear to be spurious 403 and 429 results rather than anything related to the PR.

**Comment by SethTisue** [comment]
seems good at https://scala.epfl.ch/records.html and https://scala.epfl.ch/minutes/2023/07/26/july-26-2023.html

**Pull request merged**
