### PR TITLE
Add corporate membership application table

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
@bishabosha do you know what the error means?

```
* At ./_site/records/2023-Q2-activity-report.html:350:

  External link https://github.com/sbt/sbt/pull/7298 failed (status code 403)

* At ./_site/records/2023-Q2-activity-report.html:351:

  External link https://github.com/sbt/sbt/pull/7295 failed (status code 403)
```

Looks like it flags those links as broken, but when I open them, they work. Re-running the CI didn't solve it.

**Comment by bishabosha** [comment]
maybe GitHub rejects something it believes is a CI runner

**Comment by anatoliykmetyuk** [comment]
But it wasn't doing it before?

**Comment by bishabosha** [comment]
it also had error 429 which is too many requests - so some rate limiting is being applied

**Comment by anatoliykmetyuk** [comment]
Restarting it today didn't seem to help. Looks like something was changed on GitHub's side so that the existing CI will not work.

As this error is clearly unrelated to the contents of this PR, I propose to merge this PR whenever @darjutak approves it, and debug the CI separately.

**Pull request merged**
