### PR TITLE
Hall of fame

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
A showcase of our past project that finished with success, or the current processes that we run. In other words, a showcase of impact we are making.

CleanShot 2023-09-01 at 15 47 58@2x

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
@bishabosha I need your help on this one... Could you help me figure out how to make the cards pretty?

The data still needs refinement, TBD.

**Comment by bishabosha** [comment]
how would you like it to look more pretty? maybe icons?

**Comment by anatoliykmetyuk** [comment]
> how would you like it to look more pretty? maybe icons?

Ok, I think they are fine-ish as they are. The reason I was asking is because I couldn't figure out how to align items. But I think I got it by now.

**Comment by bishabosha** [comment]
the height is too short for metals and scalafix

**Comment by iusildra** [comment]
Love it!
Maybe you could add a small legend, people might not understand the meaning of the "check" and "on-going" logos. WDYT ?

**Pull request merged**
