### PR TITLE
Add darja and use yarn

### PR DESCRIPTION
**Pull request by darjutak**

### CODE REVIEW

**Comment by jvican** [comment]
2700 lines of dependencies? w00t

**Comment by heathermiller** [comment]
Wait, why yarn? Can we just have 1 PR adding Darja?

**Comment by darjutak** [comment]
I've added myself and asked @MasseGuillaume to help out by controlling. There was an issue (I'll let him explain) and many other things got changed. I am happy to do it all over again, please advise

**Comment by heathermiller** [comment]
@darjutak could you make a new PR containing:

1. your photo
2. the following addition to team-members.yml?

```yaml
   - member: darja
     name: Darja Jovanovic
     title: Communication Manager
     email: darja.jovanovic@epfl.ch
     github: darjutak
     twitter: darjutak
     photo: /resources/img/darja.png
     currentlyWorkingOn: false
     contact_for: [scalaCenterActivities]
```

**Comment by darjutak** [comment]
@heathermiller done as advised, thanks

**Pull request closed without merging**
