### PR TITLE
Add Spotify as an Advisory Board member.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by SethTisue** [comment]
@sjrd I noticed today that the Scala Center sponsor list on the front page of scala-lang.org is out of date (e.g. Spotify is missing)

**Comment by julienrf** [comment]
Indeed, the website deployment pipeline does not seem to be working. I’m not sure who can help with this.

**Comment by SethTisue** [comment]
@julienrf which website deployment pipeline, the scala.epfl.ch one, or the scala-lang.org one?

**Comment by julienrf** [comment]
scala.epfl.ch

**Comment by SethTisue** [comment]
ah. is it Fabien?

**Comment by SethTisue** [comment]
but I'm confused why you bring it up, what is the evidence that the scala.epfl.ch pipeline is broken? my comment was about something separate on scala-lang.org

**Comment by julienrf** [comment]
Sorry, I’m just tired…!

**Comment by sjrd** [comment]
I did not even know there *was* a list of Scala Center sponsors on the scala-lang.org website ... :sweat_smile:

**Pull request merged**
